name: Deploy to DigitalOcean for MERN Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH Key Bypass
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DO_HOST }}
          USER: ${{ secrets.DO_USER }}
        run: |
          echo "Deploying to $HOST"
          ssh $USER@$HOST << EOF
            # Install necessary packages
            # sudo apt-get update
            # sudo apt-get install -y nginx nodejs npm

            # Install PM2
            # sudo npm install -g pm2

            # Set up firewall
            # sudo ufw allow OpenSSH
            # sudo ufw allow 'Nginx Full'
            # sudo ufw enable

            # Set up project directories
            # mkdir -p /var/www/mern-backend
            # mkdir -p /var/www/mern-frontend

            # Clone repository
            cd /var/www/
            git clone https://github.com/BoostrNetWave/Adethix.git

            # Install dependencies and build
            cd /var/www/server/
            npm install
            # npm run build

            # Start backend with PM2
            pm2 restart all || pm2 start app.js --name backend

            # Set up Nginx for frontend
            # sudo cp -r build/* /var/www/html/
            sudo cp -r Adethix/server/dist/* /var/www/html/
            sudo systemctl restart nginx
          EOF
